// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ef.core.json.column.Data;

#nullable disable

namespace ef.core.json.column.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240808192204_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ef.core.json.column.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("ef.core.json.column.Models.Product", b =>
                {
                    b.OwnsMany("ef.core.json.column.Models.ValueObjects.SupplierInformation", "SupplierInformations", b1 =>
                        {
                            b1.Property<int>("ProductId")
                                .HasColumnType("integer");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("ProductId", "Id");

                            b1.ToTable("Products");

                            b1.ToJson("SupplierInformations");

                            b1.WithOwner()
                                .HasForeignKey("ProductId");

                            b1.OwnsOne("ef.core.json.column.Models.ValueObjects.Address", "Address", b2 =>
                                {
                                    b2.Property<int>("SupplierInformationProductId")
                                        .HasColumnType("integer");

                                    b2.Property<int>("SupplierInformationId")
                                        .HasColumnType("integer");

                                    b2.Property<string>("City")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("Country")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("Street")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.HasKey("SupplierInformationProductId", "SupplierInformationId");

                                    b2.ToTable("Products");

                                    b2.WithOwner()
                                        .HasForeignKey("SupplierInformationProductId", "SupplierInformationId");
                                });

                            b1.Navigation("Address")
                                .IsRequired();
                        });

                    b.Navigation("SupplierInformations");
                });
#pragma warning restore 612, 618
        }
    }
}
